; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    mikalhart/TinyGPSPlus @ ^1.1.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9

; Передавач: читає дату/час з GPS (SEQURE M10-25Q), показує на дисплеї,
; відправляє по LoRa. Також обробляє натискання кнопки (HW5: FreeRTOS+Queue).
[env:transmitter]
build_flags = -D DEVICE_ROLE_TRANSMITTER
upload_port = /dev/cu.usbserial-58EF0800971
monitor_port = /dev/cu.usbserial-58EF0800971

; Приймач: слухає LoRa, показує отримані дату/час на дисплеї.
[env:receiver]
build_flags = -D DEVICE_ROLE_RECEIVER
upload_port = /dev/cu.usbserial-59260139821
monitor_port = /dev/cu.usbserial-59260139821
